Feature/members filter
antistatique/citadel pull request #220
Opened 2021-05-31 12:15 UTC by NoeBerdoz

### 💬 Describe the pull request
Ajout du filtre des projets par membres

### 🗃️ Issues
This pull request is related to :
- #120 Liste des projets et filtres simples

2021-05-31 16:06 UTC, WengerK requested changes
Pass a collection of User instead of simple array for type-hinting

2021-05-31 16:06 UTC, WengerK commented on src/Controller/ProjectsController.php
> +        $usersFromFilter = $request->query->all('users');
why naming this variable with `FromFilter ` ?

2021-05-31 16:06 UTC, WengerK commented on src/Controller/ProjectsController.php
> +            $repository->addConditionTeamMembers($projectQuery, $usersFromFilter);
If we update the fetched $users, can we then pass a Doctrine Collection as parameter ?

2021-05-31 16:06 UTC, WengerK commented on src/Repository/ProjectRepository.php
> +     */
pass array of Team (add docblock=



```suggestion
    /**
     * Filter projects according to members.
     *
     * @var Collection $members
     */
```

2021-05-31 16:06 UTC, WengerK commented on src/Controller/ProjectsController.php
> +        $usersFromFilter = $request->query->all('users');
Can we transform an array of User into a collection of Member using the `UserRepository` as we did for Shuttle ?

2021-05-31 16:06 UTC, WengerK commented on src/Repository/ProjectRepository.php
> +    public function addConditionTeamMembers(QueryBuilder $query, array $members): void
On the collection, get all the IDs and filter by

2021-06-01 06:33 UTC, WengerK commented on src/Controller/ProjectsController.php
> +                ],
```suggestion
            ],
```

2021-06-01 09:03 UTC, WengerK commented on src/Controller/ProjectsController.php
> +        $users = !in_array('', $request->query->all('users')) ? new ArrayCollection($userRepository->findBy(array('id' => $request->query->all('users')))) : null;
Can't we use `empty` instead ? 
```suggestion
        $users = !empty('', $request->query->all('users')) ? new ArrayCollection($userRepository->findBy(array('id' => $request->query->all('users')))) : null;
```

2021-06-01 09:16 UTC, NoeBerdoz commented on src/Controller/ProjectsController.php
> +        $users = !in_array('', $request->query->all('users')) ? new ArrayCollection($userRepository->findBy(array('id' => $request->query->all('users')))) : null;
No because `empty($request->query->all('users'))` returns always false as there is an array [0 => ""] when the user inputs manually no members on url like the unit tests "&users%5B%5D="

2021-06-01 11:42 UTC, merged