Feature/technology
antistatique/citadel pull request #241
Opened 2021-06-07 09:31 UTC by NoeBerdoz

### 💬 Ajout des technologies
Ajout des entités en lien avec les technologies
- Technology
- Release
- Dependency

Ajout d'un embed form dependecy dans l'édition de projet

Ajout d'une migration pour les données dans technology

### 🗃️ Issues
This pull request is related to :
- #1

2021-06-07 13:43 UTC, WengerK commented on migrations/Version20210607115734.php
> +        $this->addSql('INSERT INTO technology (name, handler) VALUES(\'Symfony\', \'https://symfony.com/\')');
Handler should be a reflection on a class not an URL

2021-06-07 13:44 UTC, WengerK commented on src/Entity/Project.php
> +     * @ORM\OneToMany(targetEntity="Domain", mappedBy="project", cascade={"persist"})
keep usage of `Domain::class`

2021-06-07 13:45 UTC, WengerK commented on src/Entity/Technology.php
> +    private ?string $handler;
handler can't be null

2021-06-07 13:51 UTC, WengerK requested changes
The created Entities does not comply with your schema

<img width="536" alt="Screenshot 2021-06-07 at 15 50 24" src="https://user-images.githubusercontent.com/1841592/121028433-1e32a200-c7a8-11eb-80d9-535f21031ffa.png">

Please update the Dependency according your initial DB schema

2021-06-07 13:51 UTC, WengerK commented on src/Entity/Release.php
> +
add a getVersion which is concat of Major, minor and patch

2021-06-07 13:52 UTC, WengerK commented on migrations/Version20210607115734.php
> +        $this->addSql('INSERT INTO technology (name, handler) VALUES(\'Symfony\', \'https://symfony.com/\')');
add `React`, `VueJS`, `Laravel`

2021-06-07 14:33 UTC, WengerK commented on src/Entity/Dependency.php
> +    private array $config = [];
```suggestion
    private ?array $config = [];
```

2021-06-07 14:38 UTC, WengerK commented on src/Entity/Release.php
> +class Release
add missing `preRelease` attribute as string, nullable.

see https://semver.org/#spec-item-9

2021-06-07 14:42 UTC, WengerK commented on src/Entity/Release.php
> +
concat getVersion with the new preRelease using an hypen (see https://semver.org/#spec-item-9)

Ensure on SET of preRelease it only contains `0-9A-Za-z-` see https://semver.org/#spec-item-9

2021-06-07 14:54 UTC, WengerK commented on src/Entity/Dependency.php
> +    private Release $projectCurrentVersion;
I would suggest

```suggestion
     * @ORM\JoinColumn()
     */
    private ?Release $projectCurrentVersion = null;
```

2021-06-07 14:54 UTC, WengerK commented on src/Entity/Dependency.php
> +    public function getProjectCurrentVersion(): Release
```suggestion
    public function getProjectCurrentVersion(): ?Release
```

2021-06-07 15:19 UTC, NoeBerdoz commented on src/Entity/Dependency.php
> +    private Release $projectCurrentVersion;
Why do you suggest to remove the release_id fk ? 
`JoinColumn(name="release_id", referencedColumnName="id", nullable=false)` -> `JoinColumn()`

2021-06-07 15:33 UTC, WengerK commented on src/Entity/Dependency.php
> +    private Release $projectCurrentVersion;
I don't want release_id as name because it's more than a rlease_id, it's the current_release. so let's doctrine name it after the attribute name instead of hardcoding the column name. same for the referencedcolumName, let's use the default which is id

but you may need to keep nullable=false I'm not confident about the fact it's nullable by default

2021-06-07 15:35 UTC, WengerK commented on src/Entity/Release.php
> +        $this->preRelease = $preRelease;
use the regex I gave you about pre-release validation before setting.

`0-9A-Za-z-` it's way less than the whole Unidcode standard as you set it.

2021-06-08 13:14 UTC, WengerK submitted a review, later dismissed

2021-06-08 13:27 UTC, merged