Feature/project domain detail
antistatique/citadel pull request #255
Opened 2021-06-15 12:45 UTC by NoeBerdoz

### 💬 Describe the pull request
Ajout des données dynamique dans le détail d'un projet pour les domaines

### 🗃️ Issues
This pull request is related to :
- #141 Formulaire d'ajout de domaine à un projet

2021-06-15 12:56 UTC, WengerK requested changes
revert ignoring .env

2021-06-15 12:56 UTC, WengerK commented on .gitignore
> +.env
you must keep `.env` !!!!

You may ignore `.env.local` if you want to create any modification localy only.

2021-06-15 13:11 UTC, NoeBerdoz commented on .gitignore
> +.env
Okay removed .env from gitignore, I didn't knew that I can setup a .env.local to work on my environement 👍

2021-06-16 18:23 UTC, WengerK approved these changes

2021-06-16 20:19 UTC, merged