add Avatar to Member on Google oAuth
antistatique/citadel pull request #273
Opened 2021-06-25 13:43 UTC by WengerK

### 💬 Describe the pull request
- add Avatar to Member on Google oAuth
- Ensure Avatar is fetched via a custom Controller to prevent sending referee and data to Google on image download

@gido can you review my fetcher process ? Does it works as it should ? Is it sufficient ?

2021-07-06 05:55 UTC, gido requested changes

2021-07-06 05:55 UTC, gido commented on src/Controller/AvatarController.php
> +        return $this->redirect($avatar);
OK, if we want to only prevent from referrer leakage we can set a [Referrer-Policy](https://web.dev/referrer-best-practices/) by adding the following header on each request response:

```
Referrer-Policy: same-origin
```

So we don't need anymore this controller and you can add the meta tag in the head of the page template or a HTTP header

2021-07-06 05:55 UTC, gido commented on templates/base.html.twig
> +                                          style="background-image: url({{ path('app_avatar_fetch', {id: app.user.id}) }})">
Add a if avatar

2021-07-06 05:55 UTC, gido commented on templates/projects/list_project.html.twig
> +                                                          style="background-image: url({{ path('app_avatar_fetch', {id: member.user.id}) }})">
Same comment

2021-07-07 07:34 UTC, WengerK commented
Thanks I made all the changes !

2021-07-07 08:12 UTC, gido approved these changes

2021-07-07 08:13 UTC, gido commented
Thanks @WengerK !

2021-07-07 08:22 UTC, merged