Command to sync project with Github
antistatique/citadel pull request #275
Opened 2021-06-25 15:53 UTC by WengerK

### 💬 Describe the pull request
- Command to sync project with Github

2021-06-25 16:14 UTC, WengerK commented on src/Command/GithubReposSyncCommand.php
> +                }
Should we skip existing project instead of fetching them and update it ?

I would suggest to simplify this command and, skip existing project.

Then rename the command ImportGithubRepository + explain in desc it skip already existing repository.

So it's kind of a "one-shot" command we may use to import in the futur new project when we forget to add them "in batch" for example.


This command may be usefull if used with #276. It would at least link the proper user on the proper project by default on 100+ projects :)

2021-06-27 09:09 UTC, WengerK commented
Should we rename this "Import" and therefore code it as a "one-shot" command or at least a not re-runnable command ? Therefore we may skip existing project instead of trying to update them according missing values

2021-07-06 05:57 UTC, gido commented on src/Command/GithubReposSyncCommand.php
> +                }
Agree on the comment. We need a one-shot command

2021-07-06 06:05 UTC, gido commented on src/Entity/Project.php
> +    private ?string $githubId = null;
I don't like it. Can we use the related tools/link to identify the GitHub Repository?

2021-07-06 06:05 UTC, gido commented on src/Command/GithubReposImportCommand.php
> +                // Skip if ID and name are not returned by Github API.
Is this a plausible scenario?

2021-07-07 12:16 UTC, WengerK commented on src/Entity/Project.php
> +    private ?string $githubId = null;
We will need the GithubId once we will add the feature (which may be enabled/disabled) to fetch last release for each project or use the "status" of the project (the yellow/green tick on Github).

2021-07-07 12:20 UTC, WengerK commented on src/Entity/Project.php
> +    private ?string $githubId = null;
Otherwise, I may use the "homepage" url given by Github. and skip a repo if any Citadel Project already have this URL as RelatedURL. 

Do you prefer this approach ?

2021-07-07 16:56 UTC, gido commented on src/Entity/Project.php
> +    private ?string $githubId = null;
We don't need the GitHub ID for checks status or releases. The "full name"(`{owner}/{name}` - `antistatique/citadel`) is enough:

 - statues: https://docs.github.com/en/rest/reference/checks#list-check-suites-for-a-git-reference
 - tags: https://docs.github.com/en/rest/reference/git#references

The owner/name can be easily extracted from a GitHub url but maybe this is not a good idea...

2021-07-13 13:50 UTC, WengerK commented on src/Entity/Project.php
> +    private ?string $githubId = null;
removed GithubID in favor of RelatedTool "Github"

2021-07-28 17:39 UTC, gido submitted a review, later dismissed
I spoted small typos in comment and technologies detection based on `npm` don't take in account yarn project. It's a limitation we need to take in account and don't prevent a merge!

2021-07-28 17:39 UTC, gido commented on src/Command/GithubReposImportCommand.php
> +                    $this->em->remove($project);
```suggestion
```

2021-07-28 17:39 UTC, gido commented on templates/macros.html.twig
> +        technology.handler == 'drupal' ? 'blue',
Not perfect ;)

2021-07-28 17:39 UTC, gido commented on src/Command/GithubReposImportCommand.php
> +        $fileExists = $githubRepo->contents()->exists($repository['owner']['login'], $repository['name'], 'package.json');
Our recent project have only a `yarn.lock` file

2021-07-28 21:14 UTC, gido approved these changes

2021-07-29 07:31 UTC, gido requested changes
j'ai testé la commande en local (avec la db de prod) et j'ai aucun projet qui a été importé:

```
 [OK] Congratulation ! 0 Github projects have been imported into Citadel.

+-------+----------+---------+-----------+---------+
| total | imported | ignored | malformed | skipped |
+-------+----------+---------+-----------+---------+
| 421   | 0        | 30      | 0         | 391     |
+-------+----------+---------+-----------+---------+
```

a investiguer

2021-07-29 07:56 UTC, gido commented on migrations/Version20210607101917.php
> +        }
ok, I found out why the import wasn't working. You can't modify an already executed migration  (on production).

We need to revert the change on this migration and create a new one that add handler.
But what we can see here is that `Technology` have no advantage to be in the database and we can simply refer to a key string stored into `Dependency` (to do the role of the current handler). Wdyt?

2021-08-06 13:09 UTC, WengerK commented on migrations/Version20210607101917.php
> +        }
I agree with you, let's do that on another PR :) I want to merge this to stop "preventing" citadel to move on

2021-08-06 13:17 UTC, merged