add Gandi importation of domains
antistatique/citadel pull request #364
Opened 2021-08-19 14:00 UTC by WengerK

### 💬 Describe the pull request
- Command to import domain(s) from Gandi

### 🔢 To Review

Steps to review the PR:

1. Set the API key on `.env`

```
###> Gandi Provider ###
GANDI_APIKEY=api_key
###< Gandi Provider ###
```

1. run the command `symfony console gandi:domain:import`

```
symfony console gandi:domain:import
docker-compose exec dev symfony console gandi:domain:import
```

### 📸 Screenshots

<img width="823" alt="Screenshot 2021-08-19 at 15 59 38" src="https://user-images.githubusercontent.com/1841592/130081993-3ce12b1e-4511-4df1-9d8d-2954617d6ac7.png">

2021-08-20 16:24 UTC, gido requested changes
You will need an access to our Gandi account to fully test this :)

thanks for the great works!!

2021-08-20 16:24 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +        $domains = $this->gandi->domain()->getList();
Also we need to filter with the `reseller_id` of Antistatique as api token are personal, it will also list my personal domain name

2021-08-20 16:24 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setIsManagedByAntistatique(true);
Hum, on Gandi we have access to some domain that we are not paying for (only have technical access) and some that we are paying but the dns zone is not managed by us.

The response of this api endpoint don't include all contacts information. Maybe a test on owner is enough to have a first filter?

2021-08-20 16:24 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setExpiresAt($expiredAt);
If the flag `autorenew` is TRUE this information is less useful

2021-08-20 16:24 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setUrl($domainRegistry['fqdn']);
Better to use `fqdn_unicode` ? Thinking of the difference if the domain name contains an accent

2021-08-21 08:04 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +        $domains = $this->gandi->domain()->getList();
Oh I did not know. Should WE use .env or you prefere command param ?

2021-08-21 08:04 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +        $domains = $this->gandi->domain()->getList();
Abouter pager inonow but Can t test with m'y own account. Should digg with a Key of Antistatique

2021-08-21 08:05 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setExpiresAt($expiredAt);
Okay, should WE add autorenew inside Citadel or juste strip thé info ?

2021-08-21 08:05 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setUrl($domainRegistry['fqdn']);
Okay

2021-08-23 06:48 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setIsManagedByAntistatique(true);
should we use 

```
    "orga_owner" => "foo"
    "owner" => "foo"
    "domain_owner" => "foo"
```

to set the `setIsManagedByAntistatique` ?

2021-08-23 09:19 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +        $domains = $this->gandi->domain()->getList();
added with an option for now

2021-08-23 15:49 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setIsManagedByAntistatique(true);
I don't know, can you check the result for the domain `cardis.ch`?

2021-08-24 07:26 UTC, WengerK commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setIsManagedByAntistatique(true);
Examples


`cardis-sothebys-realty.ch`
```
"owner" => "Cardis SA"
"domain_owner" => "Cardis SA"
"orga_owner" => "Cardis SA"
```

`lestoitsdegeneve.ch`
```
"owner" => "Antistatique"
"domain_owner" => "Antistatique.net"
"orga_owner" => "Antistatique"
```

Aussi, parmis nos 117 domaines, aucun est `owner != orga_owner`.

Est-ce qu on prend la décision de remplire le ManagedBy quand `owner != Antistatique` ?

2021-09-01 06:11 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +                }
try to apply a regexp on the whole string ?

2021-09-03 16:03 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $domain->setExpiresAt($expiredAt);
Ok for not setting the expiration if autorenew is true

2021-09-24 07:44 UTC, gido approved these changes

2021-09-24 07:44 UTC, gido commented on src/Command/GandiDomainsImportCommand.php
> +            $options['query']['reseller_id'] = $resellee;
I added the option

2021-09-24 07:44 UTC, gido approved these changes

2021-09-24 09:12 UTC, merged